"""Add JSON-as-string field for tabular data

Revision ID: c41709cff596
Revises: 90461eabd644
Create Date: 2019-02-22 17:58:28.458181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c41709cff596'
down_revision = '90461eabd644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('tabular', sa.String(length=10000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'tabular')
    # ### end Alembic commands ###
